#pragma once

#define MAGIC_ROTATION_COEFFICIENT 0.552368F
#define MAGIC_SCALE_COEFFICIENT 4096.0F

#define MAGIC_ENTITY_TO_LEVEL_PITCH_OFFSET 0.0F
#define MAGIC_ENTITY_TO_LEVEL_YAW_OFFSET 90.0F
#define MAGIC_ENTITY_TO_LEVEL_ROLL_OFFSET 0.0F

#define MAGIC_ENTITY_TO_LEVEL_SCALE_COEFFICIENT 2048.0F

#define MAGIC_UV_COEFFICIENT 16.0F

#define MAGIC_WORLD_SCALE 0.01F