option (BUILD_SHARED_LIBS OFF)
option (SQLITECPP_BUILD_TESTS OFF)
option (SQLITECPP_USE_STATIC_RUNTIME OFF)
option (SQLITECPP_USE_STACK_PROTECTION ON)
option (SQLITECPP_USE_GCOV OFF)
option (SQLITECPP_INCLUDE_SCRIPT OFF)
option (SQLITECPP_USE_ASAN OFF)
option (SQLITECPP_INTERNAL_SQLITE ON)
option (SQLITECPP_DISABLE_STD_FILESYSTEM OFF)
option (SQLITECPP_DISABLE_EXPANDED_SQL OFF)
option (SQLITECPP_RUN_CPPLINT OFF)
option (SQLITECPP_RUN_CPPCHECK OFF)
option (SQLITECPP_RUN_DOXYGEN OFF)
option (SQLITECPP_BUILD_EXAMPLES OFF)
option (SQLITE_ENABLE_COLUMN_METADATA OFF)
option (SQLITE_ENABLE_ASSERT_HANDLER OFF)
option (SQLITE_HAS_CODEC OFF)
option (SQLITE_USE_LEGACY_STRUCT OFF)
option (SQLITE_OMIT_LOAD_EXTENSION OFF)
option (SQLITE_ENABLE_RTREE OFF)
option (SQLITE_ENABLE_DBSTAT_VTAB OFF)

FetchContent_Declare (
  SQLiteCpp
  GIT_REPOSITORY "https://github.com/SRombauts/SQLiteCpp.git"
  GIT_TAG        "3.3.2"
)

set (SQLITECPP_INCLUDE_DIR "${CMAKE_BINARY_DIR}/_deps/sqlitecpp-src/include")

FetchContent_MakeAvailable (SQLiteCpp)
